# Generated by Django 2.0.2 on 2018-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='topping_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topping',
            name='topping_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
